const pool = require('../config/db');
const logActivity = require('../utils/logActivity');
const { TASK_FLOW, ALL_TASK_NAMES, TASK_NAMES, STAGE_BEFORE_TASK, getDownstreamTaskNames } = require('../utils/taskFlow');
const { closeDealWon } = require('../utils/dealLifecycle');
const { getNextDayDateString, getRandomAvailableTimeSlot } = require('../utils/scheduling');
const { validateRequiredText, validateDate, validateTime, firstError } = require('../utils/validators');

// GET /api/tasks  (joined with seller/property/assignee names for display)
exports.getAllTasks = async (req, res) => {
  try {
    const [rows] = await pool.query(`
      SELECT
        t.*,
        s.name AS seller_name,
        p.property_address AS property_address,
        emp.name AS assigned_to_name
      FROM tasks t
      JOIN sellers s ON s.id = t.seller_id
      LEFT JOIN properties p ON p.id = t.property_id
      JOIN employees emp ON emp.id = t.assigned_to
      ORDER BY t.id DESC
    `);
    res.json(rows);
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: 'Failed to load tasks.' });
  }
};

// Static list of task names for the "Edit Task" task-name dropdown
exports.getTaskOptions = (req, res) => {
  res.json(ALL_TASK_NAMES);
};

// NOTE: there is intentionally no POST /api/tasks (manual task creation) anymore.
// Every task in the system is auto-generated by the chain (see utils/taskFlow.js) or by
// the seller/property lifecycle (see sellerController / propertyController). Existing
// tasks can still be corrected via PUT (Edit Task) — e.g. reassigning, rescheduling, or
// renaming one to a different chain step — which avoids duplicate or out-of-order tasks
// that manual creation could introduce.

// PUT /api/tasks/:id  (Update/Edit Task — this is where the automation chain fires)
exports.updateTask = async (req, res) => {
  const conn = await pool.getConnection();
  try {
    const { id } = req.params;
    const { task, seller_id, property_id, task_date, task_time, assigned_to, status } = req.body;

    const [existingRows] = await conn.query('SELECT * FROM tasks WHERE id = ?', [id]);
    if (existingRows.length === 0) {
      conn.release();
      return res.status(404).json({ message: 'Task not found.' });
    }
    const existing = existingRows[0];
    const wasNotDone = existing.status !== 'Done';
    const willBeDone = status === 'Done';
    const wasDone = existing.status === 'Done';
    const willBeNotDone = status === 'Not Done';

    const finalTask = task ?? existing.task;
    const finalDate = task_date ?? existing.task_date;
    const finalTime = task_time ?? existing.task_time;

    const validationError = firstError([
      [validateRequiredText, finalTask, 'Task'],
      [validateDate, finalDate, 'Date'],
      [validateTime, finalTime, 'Time']
    ]);
    if (validationError) {
      conn.release();
      return res.status(400).json({ message: validationError });
    }

    // "Get Property Info" is locked from being un-checked once a property record exists
    // for its seller — at that point it's historical, and the property-status lifecycle
    // (see propertyController) is what eventually removes it, not manual toggling.
    if (existing.task === TASK_NAMES.GET_PROPERTY_INFO && wasDone && willBeNotDone) {
      const [propCountRows] = await conn.query(
        'SELECT COUNT(*) AS count FROM properties WHERE seller_id = ?',
        [existing.seller_id]
      );
      if (propCountRows[0].count > 0) {
        conn.release();
        return res.status(400).json({
          message: '"Get Property Info" can\'t be unchecked once a property record exists for this seller. It\'s removed automatically when the deal closes (Complete or Cancelled).'
        });
      }
    }

    // Reassignment must stay within the correct team: whichever team is already handling
    // this property (Team Texas / Team Florida), or Team Acquisition for the seller-level
    // "Get Property Info" task that isn't tied to a property yet.
    const finalAssignedTo = assigned_to ?? existing.assigned_to;
    let requiredTeam = 'Team Acquisition';
    if (existing.property_id) {
      const [propTeamRows] = await conn.query(
        `SELECT e.team FROM properties p JOIN employees e ON e.id = p.employee_id WHERE p.id = ?`,
        [existing.property_id]
      );
      if (propTeamRows.length > 0) requiredTeam = propTeamRows[0].team;
    }
    const [assigneeRows] = await conn.query('SELECT team FROM employees WHERE id = ?', [finalAssignedTo]);
    if (assigneeRows.length === 0) {
      conn.release();
      return res.status(400).json({ message: 'Selected assignee not found.' });
    }
    if (assigneeRows[0].team !== requiredTeam) {
      conn.release();
      return res.status(400).json({ message: `This task can only be assigned to an agent from ${requiredTeam}.` });
    }

    await conn.beginTransaction();

    await conn.query(
      `UPDATE tasks SET task = ?, seller_id = ?, property_id = ?, task_date = ?, task_time = ?, assigned_to = ?, status = ?
       WHERE id = ?`,
      [
        task ?? existing.task,
        seller_id ?? existing.seller_id,
        property_id ?? existing.property_id,
        task_date ?? existing.task_date,
        task_time ?? existing.task_time,
        assigned_to ?? existing.assigned_to,
        status ?? existing.status,
        id
      ]
    );

    let automationNote = '';

    // Fire automation only on the Not Done -> Done transition, for tasks that are part of the chain
    if (wasNotDone && willBeDone) {
      const finalTaskName = task ?? existing.task;
      const flow = TASK_FLOW[finalTaskName];
      const finalPropertyId = property_id ?? existing.property_id;
      const finalSellerId = seller_id ?? existing.seller_id;

      if (flow && finalPropertyId) {
        if (flow.nextTask) {
          // Advance the pipeline stage and create the next task in the chain, assigned
          // to the SAME agent on the property.
          if (flow.nextStage) {
            await conn.query(
              'UPDATE sales_pipeline SET stage = ? WHERE property_id = ?',
              [flow.nextStage, finalPropertyId]
            );
          }
          const [propRows] = await conn.query('SELECT employee_id FROM properties WHERE id = ?', [finalPropertyId]);
          const agentId = propRows[0]?.employee_id ?? (assigned_to ?? existing.assigned_to);
          const dueDate = getNextDayDateString();
          const dueTime = await getRandomAvailableTimeSlot(conn, agentId, dueDate);
          await conn.query(
            `INSERT INTO tasks (task, seller_id, property_id, task_date, task_time, assigned_to, status)
             VALUES (?, ?, ?, ?, ?, ?, 'Not Done')`,
            [flow.nextTask, finalSellerId, finalPropertyId, dueDate, dueTime, agentId]
          );
          automationNote = ` Stage advanced to "${flow.nextStage}", next task "${flow.nextTask}" created.`;
        } else if (flow.nextStage === 'Closed - Won') {
          // Terminal step of the chain — "Contract Signing" was just marked Done. This
          // closes the deal exactly the same way the Property module's "Complete" status
          // does: property status -> Complete, pipeline -> Closed - Won, every task for
          // this property (including this one) gets removed.
          automationNote = await closeDealWon(conn, { sellerId: finalSellerId, propertyId: finalPropertyId });
        }
      }
    }

    // Reverse automation: un-checking a completed chain task means everything that came
    // AFTER it is no longer valid (its prerequisite is no longer met) — remove those
    // downstream tasks and roll the pipeline stage back to where it was before this task
    // was originally completed.
    if (wasDone && willBeNotDone) {
      const finalTaskName = task ?? existing.task;
      const finalPropertyId = property_id ?? existing.property_id;
      const finalSellerId = seller_id ?? existing.seller_id;

      const downstreamNames = getDownstreamTaskNames(finalTaskName);
      const priorStage = STAGE_BEFORE_TASK[finalTaskName];

      if (finalPropertyId && downstreamNames.length > 0) {
        const [deleteResult] = await conn.query(
          `DELETE FROM tasks WHERE seller_id = ? AND property_id = ? AND task IN (${downstreamNames.map(() => '?').join(',')})`,
          [finalSellerId, finalPropertyId, ...downstreamNames]
        );
        automationNote += ` Removed ${deleteResult.affectedRows} downstream task(s) that depended on this one.`;
      }

      if (finalPropertyId && priorStage) {
        await conn.query('UPDATE sales_pipeline SET stage = ? WHERE property_id = ?', [priorStage, finalPropertyId]);
        automationNote += ` Stage reverted to "${priorStage}".`;
      }
    }

    await conn.commit();
    conn.release();

    await logActivity(req.user.id, `Task "${task ?? existing.task}" updated.${automationNote}`);

    const [rows] = await pool.query('SELECT * FROM tasks WHERE id = ?', [id]);
    if (rows.length === 0) {
      // This happens when marking "Contract Signing" Done closed the deal, which deletes
      // every task for the property — including this one.
      return res.json({ id, deleted: true, message: 'Task completed and removed as part of closing the deal.' });
    }
    res.json(rows[0]);
  } catch (err) {
    await conn.rollback();
    conn.release();
    console.error(err);
    res.status(500).json({ message: err.message || 'Failed to update task.' });
  }
};

// DELETE /api/tasks/:id
// "Get Property Info" can only be deleted manually while NO property record exists yet
// for its seller. Once a property is recorded, it's locked — the property-status
// lifecycle (Complete/Cancelled, see propertyController) is what removes it from then on,
// so there's always a consistent trail between a seller and the property that closed them.
exports.deleteTask = async (req, res) => {
  try {
    const { id } = req.params;

    const [existingRows] = await pool.query('SELECT * FROM tasks WHERE id = ?', [id]);
    if (existingRows.length === 0) {
      return res.status(404).json({ message: 'Task not found.' });
    }
    const task = existingRows[0];

    if (task.task === TASK_NAMES.GET_PROPERTY_INFO) {
      const [propCountRows] = await pool.query(
        'SELECT COUNT(*) AS count FROM properties WHERE seller_id = ?',
        [task.seller_id]
      );
      if (propCountRows[0].count > 0) {
        return res.status(400).json({
          message: '"Get Property Info" can\'t be deleted while a property record exists for this seller. It\'s removed automatically when the deal closes (Complete or Cancelled).'
        });
      }
    }

    await pool.query('DELETE FROM tasks WHERE id = ?', [id]);

    await logActivity(req.user.id, `Deleted task "${task.task}".`);

    res.json({ message: 'Task deleted.', id });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: err.sqlMessage || err.message || 'Failed to delete task.' });
  }
};





































// const pool = require('../config/db');
// const logActivity = require('../utils/logActivity');
// const { TASK_FLOW, ALL_TASK_NAMES, TASK_NAMES, STAGE_BEFORE_TASK, getDownstreamTaskNames } = require('../utils/taskFlow');
// const { closeDealWon } = require('../utils/dealLifecycle');
// const { validateRequiredText, validateDate, validateTime, firstError } = require('../utils/validators');

// // GET /api/tasks  (joined with seller/property/assignee names for display)
// exports.getAllTasks = async (req, res) => {
//   try {
//     const [rows] = await pool.query(`
//       SELECT
//         t.*,
//         s.name AS seller_name,
//         p.property_address AS property_address,
//         emp.name AS assigned_to_name
//       FROM tasks t
//       JOIN sellers s ON s.id = t.seller_id
//       LEFT JOIN properties p ON p.id = t.property_id
//       JOIN employees emp ON emp.id = t.assigned_to
//       ORDER BY t.id DESC
//     `);
//     res.json(rows);
//   } catch (err) {
//     console.error(err);
//     res.status(500).json({ message: 'Failed to load tasks.' });
//   }
// };

// // Static list of task names for the "Edit Task" task-name dropdown
// exports.getTaskOptions = (req, res) => {
//   res.json(ALL_TASK_NAMES);
// };

// // NOTE: there is intentionally no POST /api/tasks (manual task creation) anymore.
// // Every task in the system is auto-generated by the chain (see utils/taskFlow.js) or by
// // the seller/property lifecycle (see sellerController / propertyController). Existing
// // tasks can still be corrected via PUT (Edit Task) — e.g. reassigning or rescheduling
// // — which avoids duplicate or out-of-order tasks that manual creation could introduce.

// // PUT /api/tasks/:id  (Update/Edit Task — this is where the automation chain fires)
// exports.updateTask = async (req, res) => {
//   const conn = await pool.getConnection();
//   try {
//     const { id } = req.params;
//     const { task, seller_id, property_id, task_date, task_time, assigned_to, status } = req.body;

//     const [existingRows] = await conn.query('SELECT * FROM tasks WHERE id = ?', [id]);
//     if (existingRows.length === 0) {
//       conn.release();
//       return res.status(404).json({ message: 'Task not found.' });
//     }
//     const existing = existingRows[0];
//     const wasNotDone = existing.status !== 'Done';
//     const willBeDone = status === 'Done';
//     const wasDone = existing.status === 'Done';
//     const willBeNotDone = status === 'Not Done';

//     const finalTask = task ?? existing.task;
//     const finalDate = task_date ?? existing.task_date;
//     const finalTime = task_time ?? existing.task_time;

//     const validationError = firstError([
//       [validateRequiredText, finalTask, 'Task'],
//       [validateDate, finalDate, 'Date'],
//       [validateTime, finalTime, 'Time']
//     ]);
//     if (validationError) {
//       conn.release();
//       return res.status(400).json({ message: validationError });
//     }

//     // "Get Property Info" is locked from being un-checked once a property record exists
//     // for its seller — at that point it's historical, and the property-status lifecycle
//     // (see propertyController) is what eventually removes it, not manual toggling.
//     if (existing.task === TASK_NAMES.GET_PROPERTY_INFO && wasDone && willBeNotDone) {
//       const [propCountRows] = await conn.query(
//         'SELECT COUNT(*) AS count FROM properties WHERE seller_id = ?',
//         [existing.seller_id]
//       );
//       if (propCountRows[0].count > 0) {
//         conn.release();
//         return res.status(400).json({
//           message: '"Get Property Info" can\'t be unchecked once a property record exists for this seller. It\'s removed automatically when the deal closes (Complete or Cancelled).'
//         });
//       }
//     }

//     // Reassignment must stay within the correct team: whichever team is already handling
//     // this property (Team Texas / Team Florida), or Team Acquisition for the seller-level
//     // "Get Property Info" task that isn't tied to a property yet.
//     const finalAssignedTo = assigned_to ?? existing.assigned_to;
//     let requiredTeam = 'Team Acquisition';
//     if (existing.property_id) {
//       const [propTeamRows] = await conn.query(
//         `SELECT e.team FROM properties p JOIN employees e ON e.id = p.employee_id WHERE p.id = ?`,
//         [existing.property_id]
//       );
//       if (propTeamRows.length > 0) requiredTeam = propTeamRows[0].team;
//     }
//     const [assigneeRows] = await conn.query('SELECT team FROM employees WHERE id = ?', [finalAssignedTo]);
//     if (assigneeRows.length === 0) {
//       conn.release();
//       return res.status(400).json({ message: 'Selected assignee not found.' });
//     }
//     if (assigneeRows[0].team !== requiredTeam) {
//       conn.release();
//       return res.status(400).json({ message: `This task can only be assigned to an agent from ${requiredTeam}.` });
//     }

//     await conn.beginTransaction();

//     await conn.query(
//       `UPDATE tasks SET task = ?, seller_id = ?, property_id = ?, task_date = ?, task_time = ?, assigned_to = ?, status = ?
//        WHERE id = ?`,
//       [
//         task ?? existing.task,
//         seller_id ?? existing.seller_id,
//         property_id ?? existing.property_id,
//         task_date ?? existing.task_date,
//         task_time ?? existing.task_time,
//         assigned_to ?? existing.assigned_to,
//         status ?? existing.status,
//         id
//       ]
//     );

//     let automationNote = '';

//     // Fire automation only on the Not Done -> Done transition, for tasks that are part of the chain
//     if (wasNotDone && willBeDone) {
//       const finalTaskName = task ?? existing.task;
//       const flow = TASK_FLOW[finalTaskName];
//       const finalPropertyId = property_id ?? existing.property_id;
//       const finalSellerId = seller_id ?? existing.seller_id;

//       if (flow && finalPropertyId) {
//         if (flow.nextTask) {
//           // Advance the pipeline stage and create the next task in the chain, assigned
//           // to the SAME agent on the property.
//           if (flow.nextStage) {
//             await conn.query(
//               'UPDATE sales_pipeline SET stage = ? WHERE property_id = ?',
//               [flow.nextStage, finalPropertyId]
//             );
//           }
//           const [propRows] = await conn.query('SELECT employee_id FROM properties WHERE id = ?', [finalPropertyId]);
//           const agentId = propRows[0]?.employee_id ?? (assigned_to ?? existing.assigned_to);
//           const today = new Date().toISOString().slice(0, 10);
//           await conn.query(
//             `INSERT INTO tasks (task, seller_id, property_id, task_date, task_time, assigned_to, status)
//              VALUES (?, ?, ?, ?, '09:00:00', ?, 'Not Done')`,
//             [flow.nextTask, finalSellerId, finalPropertyId, today, agentId]
//           );
//           automationNote = ` Stage advanced to "${flow.nextStage}", next task "${flow.nextTask}" created.`;
//         } else if (flow.nextStage === 'Closed - Won') {
//           // Terminal step of the chain — "Contract Signing" was just marked Done. This
//           // closes the deal exactly the same way the Property module's "Complete" status
//           // does: property status -> Complete, pipeline -> Closed - Won, every task for
//           // this property (including this one) gets removed.
//           automationNote = await closeDealWon(conn, { sellerId: finalSellerId, propertyId: finalPropertyId });
//         }
//       }
//     }

//     // Reverse automation: un-checking a completed chain task means everything that came
//     // AFTER it is no longer valid (its prerequisite is no longer met) — remove those
//     // downstream tasks and roll the pipeline stage back to where it was before this task
//     // was originally completed.
//     if (wasDone && willBeNotDone) {
//       const finalTaskName = task ?? existing.task;
//       const finalPropertyId = property_id ?? existing.property_id;
//       const finalSellerId = seller_id ?? existing.seller_id;

//       const downstreamNames = getDownstreamTaskNames(finalTaskName);
//       const priorStage = STAGE_BEFORE_TASK[finalTaskName];

//       if (finalPropertyId && downstreamNames.length > 0) {
//         const [deleteResult] = await conn.query(
//           `DELETE FROM tasks WHERE seller_id = ? AND property_id = ? AND task IN (${downstreamNames.map(() => '?').join(',')})`,
//           [finalSellerId, finalPropertyId, ...downstreamNames]
//         );
//         automationNote += ` Removed ${deleteResult.affectedRows} downstream task(s) that depended on this one.`;
//       }

//       if (finalPropertyId && priorStage) {
//         await conn.query('UPDATE sales_pipeline SET stage = ? WHERE property_id = ?', [priorStage, finalPropertyId]);
//         automationNote += ` Stage reverted to "${priorStage}".`;
//       }
//     }

//     await conn.commit();
//     conn.release();

//     await logActivity(req.user.id, `Task "${task ?? existing.task}" updated.${automationNote}`);

//     const [rows] = await pool.query('SELECT * FROM tasks WHERE id = ?', [id]);
//     if (rows.length === 0) {
//       // This happens when marking "Contract Signing" Done closed the deal, which deletes
//       // every task for the property — including this one.
//       return res.json({ id, deleted: true, message: 'Task completed and removed as part of closing the deal.' });
//     }
//     res.json(rows[0]);
//   } catch (err) {
//     await conn.rollback();
//     conn.release();
//     console.error(err);
//     res.status(500).json({ message: err.message || 'Failed to update task.' });
//   }
// };

// // DELETE /api/tasks/:id
// // "Get Property Info" can only be deleted manually while NO property record exists yet
// // for its seller. Once a property is recorded, it's locked — the property-status
// // lifecycle (Complete/Cancelled, see propertyController) is what removes it from then on,
// // so there's always a consistent trail between a seller and the property that closed them.
// exports.deleteTask = async (req, res) => {
//   try {
//     const { id } = req.params;

//     const [existingRows] = await pool.query('SELECT * FROM tasks WHERE id = ?', [id]);
//     if (existingRows.length === 0) {
//       return res.status(404).json({ message: 'Task not found.' });
//     }
//     const task = existingRows[0];

//     if (task.task === TASK_NAMES.GET_PROPERTY_INFO) {
//       const [propCountRows] = await pool.query(
//         'SELECT COUNT(*) AS count FROM properties WHERE seller_id = ?',
//         [task.seller_id]
//       );
//       if (propCountRows[0].count > 0) {
//         return res.status(400).json({
//           message: '"Get Property Info" can\'t be deleted while a property record exists for this seller. It\'s removed automatically when the deal closes (Complete or Cancelled).'
//         });
//       }
//     }

//     await pool.query('DELETE FROM tasks WHERE id = ?', [id]);

//     await logActivity(req.user.id, `Deleted task "${task.task}".`);

//     res.json({ message: 'Task deleted.', id });
//   } catch (err) {
//     console.error(err);
//     res.status(500).json({ message: err.sqlMessage || err.message || 'Failed to delete task.' });
//   }
// };





// const pool = require('../config/db');
// const logActivity = require('../utils/logActivity');
// const { TASK_FLOW, ALL_TASK_NAMES, TASK_NAMES, STAGE_BEFORE_TASK, getDownstreamTaskNames } = require('../utils/taskFlow');
// const { closeDealWon } = require('../utils/dealLifecycle');
// const { validateRequiredText, validateDate, validateTime, firstError } = require('../utils/validators');

// // GET /api/tasks  (joined with seller/property/assignee names for display)
// exports.getAllTasks = async (req, res) => {
//   try {
//     const [rows] = await pool.query(`
//       SELECT
//         t.*,
//         s.name AS seller_name,
//         p.property_address AS property_address,
//         emp.name AS assigned_to_name
//       FROM tasks t
//       JOIN sellers s ON s.id = t.seller_id
//       LEFT JOIN properties p ON p.id = t.property_id
//       JOIN employees emp ON emp.id = t.assigned_to
//       ORDER BY t.id DESC
//     `);
//     res.json(rows);
//   } catch (err) {
//     console.error(err);
//     res.status(500).json({ message: 'Failed to load tasks.' });
//   }
// };

// // Static list of task names for the "Edit Task" task-name dropdown
// exports.getTaskOptions = (req, res) => {
//   res.json(ALL_TASK_NAMES);
// };

// // NOTE: there is intentionally no POST /api/tasks (manual task creation) anymore.
// // Every task in the system is auto-generated by the chain (see utils/taskFlow.js) or by
// // the seller/property lifecycle (see sellerController / propertyController). Existing
// // tasks can still be corrected via PUT (Edit Task) — e.g. reassigning, rescheduling, or
// // renaming one to a different chain step — which avoids duplicate or out-of-order tasks
// // that manual creation could introduce.

// // PUT /api/tasks/:id  (Update/Edit Task — this is where the automation chain fires)
// exports.updateTask = async (req, res) => {
//   const conn = await pool.getConnection();
//   try {
//     const { id } = req.params;
//     const { task, seller_id, property_id, task_date, task_time, assigned_to, status } = req.body;

//     const [existingRows] = await conn.query('SELECT * FROM tasks WHERE id = ?', [id]);
//     if (existingRows.length === 0) {
//       conn.release();
//       return res.status(404).json({ message: 'Task not found.' });
//     }
//     const existing = existingRows[0];
//     const wasNotDone = existing.status !== 'Done';
//     const willBeDone = status === 'Done';
//     const wasDone = existing.status === 'Done';
//     const willBeNotDone = status === 'Not Done';

//     const finalTask = task ?? existing.task;
//     const finalDate = task_date ?? existing.task_date;
//     const finalTime = task_time ?? existing.task_time;

//     const validationError = firstError([
//       [validateRequiredText, finalTask, 'Task'],
//       [validateDate, finalDate, 'Date'],
//       [validateTime, finalTime, 'Time']
//     ]);
//     if (validationError) {
//       conn.release();
//       return res.status(400).json({ message: validationError });
//     }

//     // "Get Property Info" is locked from being un-checked once a property record exists
//     // for its seller — at that point it's historical, and the property-status lifecycle
//     // (see propertyController) is what eventually removes it, not manual toggling.
//     if (existing.task === TASK_NAMES.GET_PROPERTY_INFO && wasDone && willBeNotDone) {
//       const [propCountRows] = await conn.query(
//         'SELECT COUNT(*) AS count FROM properties WHERE seller_id = ?',
//         [existing.seller_id]
//       );
//       if (propCountRows[0].count > 0) {
//         conn.release();
//         return res.status(400).json({
//           message: '"Get Property Info" can\'t be unchecked once a property record exists for this seller. It\'s removed automatically when the deal closes (Complete or Cancelled).'
//         });
//       }
//     }

//     await conn.beginTransaction();

//     await conn.query(
//       `UPDATE tasks SET task = ?, seller_id = ?, property_id = ?, task_date = ?, task_time = ?, assigned_to = ?, status = ?
//        WHERE id = ?`,
//       [
//         task ?? existing.task,
//         seller_id ?? existing.seller_id,
//         property_id ?? existing.property_id,
//         task_date ?? existing.task_date,
//         task_time ?? existing.task_time,
//         assigned_to ?? existing.assigned_to,
//         status ?? existing.status,
//         id
//       ]
//     );

//     let automationNote = '';

//     // Fire automation only on the Not Done -> Done transition, for tasks that are part of the chain
//     if (wasNotDone && willBeDone) {
//       const finalTaskName = task ?? existing.task;
//       const flow = TASK_FLOW[finalTaskName];
//       const finalPropertyId = property_id ?? existing.property_id;
//       const finalSellerId = seller_id ?? existing.seller_id;

//       if (flow && finalPropertyId) {
//         if (flow.nextTask) {
//           // Advance the pipeline stage and create the next task in the chain, assigned
//           // to the SAME agent on the property.
//           if (flow.nextStage) {
//             await conn.query(
//               'UPDATE sales_pipeline SET stage = ? WHERE property_id = ?',
//               [flow.nextStage, finalPropertyId]
//             );
//           }
//           const [propRows] = await conn.query('SELECT employee_id FROM properties WHERE id = ?', [finalPropertyId]);
//           const agentId = propRows[0]?.employee_id ?? (assigned_to ?? existing.assigned_to);
//           const today = new Date().toISOString().slice(0, 10);
//           await conn.query(
//             `INSERT INTO tasks (task, seller_id, property_id, task_date, task_time, assigned_to, status)
//              VALUES (?, ?, ?, ?, '09:00:00', ?, 'Not Done')`,
//             [flow.nextTask, finalSellerId, finalPropertyId, today, agentId]
//           );
//           automationNote = ` Stage advanced to "${flow.nextStage}", next task "${flow.nextTask}" created.`;
//         } else if (flow.nextStage === 'Closed - Won') {
//           // Terminal step of the chain — "Contract Signing" was just marked Done. This
//           // closes the deal exactly the same way the Property module's "Complete" status
//           // does: property status -> Complete, pipeline -> Closed - Won, every task for
//           // this property (including this one) gets removed.
//           automationNote = await closeDealWon(conn, { sellerId: finalSellerId, propertyId: finalPropertyId });
//         }
//       }
//     }

//     // Reverse automation: un-checking a completed chain task means everything that came
//     // AFTER it is no longer valid (its prerequisite is no longer met) — remove those
//     // downstream tasks and roll the pipeline stage back to where it was before this task
//     // was originally completed.
//     if (wasDone && willBeNotDone) {
//       const finalTaskName = task ?? existing.task;
//       const finalPropertyId = property_id ?? existing.property_id;
//       const finalSellerId = seller_id ?? existing.seller_id;

//       const downstreamNames = getDownstreamTaskNames(finalTaskName);
//       const priorStage = STAGE_BEFORE_TASK[finalTaskName];

//       if (finalPropertyId && downstreamNames.length > 0) {
//         const [deleteResult] = await conn.query(
//           `DELETE FROM tasks WHERE seller_id = ? AND property_id = ? AND task IN (${downstreamNames.map(() => '?').join(',')})`,
//           [finalSellerId, finalPropertyId, ...downstreamNames]
//         );
//         automationNote += ` Removed ${deleteResult.affectedRows} downstream task(s) that depended on this one.`;
//       }

//       if (finalPropertyId && priorStage) {
//         await conn.query('UPDATE sales_pipeline SET stage = ? WHERE property_id = ?', [priorStage, finalPropertyId]);
//         automationNote += ` Stage reverted to "${priorStage}".`;
//       }
//     }

//     await conn.commit();
//     conn.release();

//     await logActivity(req.user.id, `Task "${task ?? existing.task}" updated.${automationNote}`);

//     const [rows] = await pool.query('SELECT * FROM tasks WHERE id = ?', [id]);
//     if (rows.length === 0) {
//       // This happens when marking "Contract Signing" Done closed the deal, which deletes
//       // every task for the property — including this one.
//       return res.json({ id, deleted: true, message: 'Task completed and removed as part of closing the deal.' });
//     }
//     res.json(rows[0]);
//   } catch (err) {
//     await conn.rollback();
//     conn.release();
//     console.error(err);
//     res.status(500).json({ message: err.message || 'Failed to update task.' });
//   }
// };

// // DELETE /api/tasks/:id
// // "Get Property Info" can only be deleted manually while NO property record exists yet
// // for its seller. Once a property is recorded, it's locked — the property-status
// // lifecycle (Complete/Cancelled, see propertyController) is what removes it from then on,
// // so there's always a consistent trail between a seller and the property that closed them.
// exports.deleteTask = async (req, res) => {
//   try {
//     const { id } = req.params;

//     const [existingRows] = await pool.query('SELECT * FROM tasks WHERE id = ?', [id]);
//     if (existingRows.length === 0) {
//       return res.status(404).json({ message: 'Task not found.' });
//     }
//     const task = existingRows[0];

//     if (task.task === TASK_NAMES.GET_PROPERTY_INFO) {
//       const [propCountRows] = await pool.query(
//         'SELECT COUNT(*) AS count FROM properties WHERE seller_id = ?',
//         [task.seller_id]
//       );
//       if (propCountRows[0].count > 0) {
//         return res.status(400).json({
//           message: '"Get Property Info" can\'t be deleted while a property record exists for this seller. It\'s removed automatically when the deal closes (Complete or Cancelled).'
//         });
//       }
//     }

//     await pool.query('DELETE FROM tasks WHERE id = ?', [id]);

//     await logActivity(req.user.id, `Deleted task "${task.task}".`);

//     res.json({ message: 'Task deleted.', id });
//   } catch (err) {
//     console.error(err);
//     res.status(500).json({ message: err.sqlMessage || err.message || 'Failed to delete task.' });
//   }
// };