const router = require('express').Router();
const requireAuth = require('../middleware/auth');
const { getAllTasks, updateTask, deleteTask, getTaskOptions } = require('../controllers/taskController');

router.use(requireAuth);
router.get('/', getAllTasks);
router.get('/options', getTaskOptions);
router.put('/:id', updateTask);
router.delete('/:id', deleteTask);
// No POST route: manual task creation has been removed. Every task is auto-generated by
// the chain (utils/taskFlow.js) or by the seller/property lifecycle. Existing tasks can
// still be corrected via PUT.

module.exports = router;